# 5 NumPy Functions You Might Not Know.


## Well Let's First Understand What is NumPy?

![](https://www.machinelearningplus.com/wp-content/uploads/2021/10/Numpy_Feature_Image-min.png)

- NumPy is a Python Package Which Stands for "Numerical Python".
- This was Created in 2005 by Travis Oliphant.
- NumPy is Often Called as an Alternative For MatLab(a Programming Platform Designed Specifically For Engineers, and Scientists For Data Analysis, Developing Algorithm, Create Models and Application etc).
- Numpy is Used With Packages Like Scipy(Scientific Python) and Mat-Plotlib(Plotting Library) and This Makes it Capable to Replace MATLAB.


- Using NumPy We Can Perform the Following Functionalities:
  1. Mathematical and Logical Calculations Array.
  2. Fourier Transforms and Routines for Shape Manipulation.
  3. It has Built in Functions For Linear Algebra Random Number Generation.
  4. Used For Scientific Calculations.
  5. It is Faster Than Python List.
  6. It is Faster Because It is Associated With C or C++ Language.

![](https://techvidvan.com/tutorials/wp-content/uploads/sites/2/2020/07/Uses-of-NumPy-1.jpg)
  

## Let's Dive into some Practical Applications Where NumPy Has Used :

### FIRST IMAGE OF A BLACK HOLE
![](https://numpy.org/images/content_images/cs/blackhole.jpg)

##### Role OF NumPy:
The eht-imaging Python package provides tools for simulating and performing image reconstruction on VLBI data. NumPy is at the core of array data processing used in this package.

The efficient and adaptable n-dimensional array that is NumPy’s central feature enabled researchers to manipulate large numerical datasets, providing a foundation for the first-ever image of a black hole. A landmark moment in science, it gives stunning visual evidence of Einstein’s theory. 



### NUMPY’S ROLE IN THE DETECTION OF GRAVITATIONAL WAVES
![](https://numpy.org/images/content_images/cs/gw_sxs_image.png)

##### Role OF NumPy:
Gravitational waves emitted from the merger cannot be computed using any technique except brute force numerical relativity using supercomputers. The amount of data LIGO collects is as incomprehensibly large as gravitational wave signals are small.

NumPy, the standard numerical analysis package for Python, was utilized by the software used for various tasks performed during the GW detection project at LIGO. NumPy helped in solving complex maths and data manipulation at high speed. Here are some examples:

- Signal Processing: Glitch detection, Noise identification and Data Characterization (NumPy, scikit-learn, scipy, matplotlib, pandas, pyCharm)
- Data retrieval: Deciding which data can be analyzed, figuring out whether it contains a signal - needle in a haystack
- Statistical analysis: estimate the statistical significance of observational data, estimating the signal parameters (e.g. masses of stars, spin velocity, and distance) by comparison with a model.
- Visualization of data
  (Time series and
  Spectrograms)
- Compute Correlations
- Key Software developed in GW data analysis such as GwPy and PyCBC uses NumPy and AstroPy under the hood for providing object based interfaces to utilities, tools, and methods for studying data from gravitational-wave detectors.

### CRICKET ANALYTICS
![](https://numpy.org/images/content_images/cs/ipl-stadium.png)

##### Role Of NumPy
Sports Analytics is a thriving field. Many researchers and companies use NumPy and other PyData packages like Scikit-learn, SciPy, Matplotlib, and Jupyter, besides using the latest machine learning and AI techniques. NumPy has been used for various kinds of cricket related sporting analytics such as:

- **Statistical Analysis**: NumPy’s numerical capabilities help estimate the statistical significance of observational data or match events in the context of various player and game tactics, estimating the game outcome by comparison with a generative or static model. Causal analysis and big data approaches are used for tactical analysis.

- __Data Visualization__: Data graphing and visualization provide useful insights into relationship between various datasets.

## Now Let's Talk About The Functions Which We Are Going To Discuss.

- numpy.linalg.det - It Computes the Determinant of an Array.
- numpy.linalg.eig - It Computes the Eigenvalues and Right Eigenvectors of a Square Array.
- numpy.cumsum - It Gives the Commutative Sum of the Elements Along a Given Axis.
- numpy.cumprod - It Gives the Commutative Product of Element Along a Given Axis.
- numpy.matmul - It Gives the Matrix Product of Two Arrays.

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

###### Note : We will use the `Jovian` library and its `commit()` function throughout the code to save our progress as we move along.

In [1]:
!pip install jovian --upgrade -q

import jovian

jovian.commit(project='5 NumPy Functions You Might Not Know.')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "deepakkumawat2120/5-numpy-functions-you-might-not-know" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know


'https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

## Function 1 - numpy.linalg.det

#### numpy.linalg.det - It Computes the Determinant of an Array.

*Syntax: numpy.linalg.det()* 

*Parameter: An square array.*

*Return: The determinant of that square array* 


![](https://slidetodoc.com/presentation_image_h2/80afd8549109e72c2c9d126a685906f5/image-13.jpg )

In [3]:
# Example 1 - working

# creating a 2X2 Numpy matrix
n_array = np.array([[1,2],
              [3,4]])
# Displaying the array
print("Numpy Matrix is:")
print(n_array)

# Calculating the determinant of matrix
result =  np.linalg.det(n_array)

print("Determinant of given 2X2 square matrix:")
print(int(result))

Numpy Matrix is:
[[1 2]
 [3 4]]
Determinant of given 2X2 square matrix:
-2


Here We First Take a `2x2` Matrix and Create a NumPy Array of That Matrix, Assign That to Variable "n_array", Then We Use the Function `np.linalg.det` to Compute the Determinant of "n_array", Which gives us `-2` as the Determinant.

In [4]:
# Example 2 - working

# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 3X3 square matrix:")
print(int(det))

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Determinant of given 3X3 square matrix:
137180


Here We First Take a `3x3` Matrix and Create a NumPy array of it, Assign That Value to a Variable Called `n_array`, Then Compute the Determinant of That "n_array", Store That in `det` Variable and Print the Result.  

In [5]:
# Example-3  - working

# creating a 5X5 Numpy matrix
n_array = np.array([[5, 2, 1, 4, 6],
                    [9, 4, 2, 5, 2],
                    [11, 5, 7, 3, 9],
                    [5, 6, 6, 7, 2],
                    [7, 5, 9, 3, 3]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 5X5 square matrix:")
print(int(det))

Numpy Matrix is:
[[ 5  2  1  4  6]
 [ 9  4  2  5  2]
 [11  5  7  3  9]
 [ 5  6  6  7  2]
 [ 7  5  9  3  3]]

Determinant of given 5X5 square matrix:
-2003


Here We have Taken Another Example of a `5X5` Matrix and Compute the Determinant of That Matrix.

##### Example 4- breaking

In [6]:
# creating a 2X2 Numpy matrix
n_array = np.array([[2],
              [3,4]])
# Displaying the array
print("Numpy Matrix is:")
print(n_array)

# Calculating the determinant of matrix
result =  np.linalg.det(n_array)

print("Determinant of given 2X2 square matrix:")
print(int(result))

Numpy Matrix is:
[list([2]) list([3, 4])]


/tmp/ipykernel_35/791310156.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  n_array = np.array([[2],


LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

##### How to resolve it- 

Here We got an Error That we have given a 1-Dimensional Array, So Resolve This Issue We Must take an Square array as we Have Done in The Above Examples.


numpy.linalg.det is a very useful function and it Can be used anywhere to compute the `Determinant` of a square Array.

In [5]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "deepakkumawat2120/5-numpy-functions-you-might-not-know" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know


'https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know'

## Function 2 - numpy.linalg.eig

#### numpy.linalg.eig - It Computes the Determinant of an Array.

*Syntax: numpy.linalg.eig()* 

*Parameter: An square array.*

*Return: It will return two values first is eigenvalues and second is eigenvectors.*

In [8]:
# Example 1 - working

mat = np.mat("1 -2;1 3")
  
# Original matrix
print(mat)
print("")
evalue, evect = np.linalg.eig(mat)
  
# Eigenvalues of the said matrix"
print(evalue)
print("")
  
# Eigenvectors of the said matrix
print(evect)

[[ 1 -2]
 [ 1  3]]

[2.+1.j 2.-1.j]

[[ 0.81649658+0.j          0.81649658-0.j        ]
 [-0.40824829-0.40824829j -0.40824829+0.40824829j]]


In the Example 1, We have Taken a Square Array using `np.mat` function and assign That to "mat" Variable and the we have used `np.lianalg.eig` function to compute the `eigen` value but this function given us the `eig value and eigen vector` which we have taken in the variable "evalue and evector" respectively, and print those eigen values and eigen Functions.

In [9]:
# Example 2 - working

mat = np.mat("1 2 3;1 3 4;3 2 1")
  
# Original matrix
print(mat)
print("")
evalue, evect = np.linalg.eig(mat)
  
# Eigenvalues of the said matrix"
print(evalue)
print("")
  
# Eigenvectors of the said matrix
print(evect)

[[1 2 3]
 [1 3 4]
 [3 2 1]]

[ 6.70156212  0.29843788 -2.        ]

[[-0.5113361  -0.42932334 -0.40482045]
 [-0.69070311  0.7945835  -0.52048344]
 [-0.5113361  -0.42932334  0.75180941]]


Here is another Example of computing the `Eigen values and Eigen vectors` of a square array of `3x3`.

##### Example 3 - Breaking

In [10]:
mat = np.mat("1 2 ;4  6;5  2")
  
# Original matrix
print(mat)
print("")
evalue, evect = np.linalg.eig(mat)
  
# Eigenvalues of the said matrix"
print(evalue)
print("")
  
# Eigenvectors of the said matrix
print(evect)

[[1 2]
 [4 6]
 [5 2]]



LinAlgError: Last 2 dimensions of the array must be square

##### How to reslove It -
Here Again we trying to get the " Eigen Values and Eigen Vectors " of the given Array but we failed to get it because it was not a "Square Array" so to get the " Eigen Values and Eigen Vectors " we Need to make it as square as shown in the above two examples.

`np.linalg.eig` is a very useful function to compute the `eigen` values and `eigen` Vectors for an square array and it is going to compute the results in a very less period of time.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Function 3 - np.cumsum

#### numpy.cumsum - It Gives the Commutative Sum of the Elements Along a Given Axis.
*Syntax : numpy.cumsum(arr, axis=None, dtype=None, out=None)*


*Parameters* :
- *arr : [array_like] Array containing numbers whose cumulative sum is desired. If arr is not an array, a conversion is attempted.*

- *axis : Axis along which the cumulative sum is computed. The default is to compute the sum of the flattened array.*

- *dtype : Type of the returned array, as well as of the accumulator in which the elements are multiplied. If dtype is not specified, it defaults to the dtype of arr, unless arr has an integer dtype with a precision less than that of the default platform integer. In that case, the default platform integer is used instead.*

- *out : [ndarray, optional] A location into which the result is stored.
  -> If provided, it must have a shape that the inputs broadcast to.
  -> If not provided or None, a freshly-allocated array is returned*
  
  
*Return : A new array holding the result is returned unless out is specified, in which case it is returned.*

In [12]:
# Example 1 - working

Number = 10
  
print ("Input  number : ", Number)
    
Result = np.cumsum(Number) 
print ("cumulative sum of input number : ", Result) 

Input  number :  10
cumulative sum of input number :  [10]


In the Example above we are going to compute the " Cumulative Sum " of the Given number Using the function `np.cumsum` and print the result of the function, So as we did above, We have taken a number and store that in a variable called " Number " then we computed the " Cumulative sum " on that number and store that in the variable called " Result " and Print the Result.

In [13]:
# Example 2 - working

Numbers = np.array([[2, 4, 6], [1, 3, 5]])
   
print ("Input array : ",Numbers) 
    
Result = np.cumsum(Numbers) 
print ("cumulative sum of array elements: ", Result) 

Input array :  [[2 4 6]
 [1 3 5]]
cumulative sum of array elements:  [ 2  6 12 13 16 21]


Here we are going to compute the " Cumulative Sum " on an NumPy array and store the Result in the "Result" Variable and Print that Result. but here we see can that the Result is Computed in the single list of array elements.

In [14]:
# Example 3 - Working

Numbers = np.array([[2, 4, 6], [1, 3, 5]])
   
print ("Input array : ", Numbers) 
    
Result = np.cumsum(Numbers, axis = 1) 
print ("cumulative sum of array elements taking axis 1: ", Result)

Input array :  [[2 4 6]
 [1 3 5]]
cumulative sum of array elements taking axis 1:  [[ 2  6 12]
 [ 1  4  9]]


In the Example above we have computed the results of NumPy Array by `np.cumsum` fuction but here we have given the " axis = 1 " so the results is going to be computed Column Wise. 

In [15]:
# Example 4 - working

Numbers = np.array([[2, 4, 6], [1, 3, 5]])
   
print ("Input array : ", Numbers) 
    
Result = np.cumsum(Numbers, axis = 0) 
print ("cumulative sum of array elements taking axis 1: ", Result)

Input array :  [[2 4 6]
 [1 3 5]]
cumulative sum of array elements taking axis 1:  [[ 2  4  6]
 [ 3  7 11]]


Examples 4 Shows the Computation of `np.cumsum` Function on an NumPy array by keeping the " axis = 0 " which will compute the Result Row Wise.

##### Example 5 - Breaking


In [16]:
Numbers = np.array([[2, 4, 6], [ 3, 5]])
   
print ("Input array : ", Numbers) 
    
Result = np.cumsum(Numbers, axis = 0) 
print ("cumulative sum of array elements taking axis 1: ", Result)

Input array :  [list([2, 4, 6]) list([3, 5])]
cumulative sum of array elements taking axis 1:  [list([2, 4, 6]) list([2, 4, 6, 3, 5])]


/tmp/ipykernel_35/3469378645.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  Numbers = np.array([[2, 4, 6], [ 3, 5]])


##### How to resolve it-
As we can see in the above example we have given the Array of different lengths so the function `np.cumsum` does not able to compute the Cumulative Sum of the given array, So to perform this computation we need to take the Arrays of same length as we have taken in the above four Examples.


`numpy.cumsum` is a very useful function to compute the cumulative sum of given Arrays and it's very easy to use  and compute results in a very short time. 

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "deepakkumawat2120/5-numpy-functions-you-might-not-know" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know


'https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know'

## Function 4 - numpy.cumprod

#### numpy.cumprod - It Gives the Commutative Product of Element Along a Given Axis.

*Syntax : numpy.cumprod(arr, axis=None, dtype=None, out=None)*

*Parameters* :
- *arr : [array_like] Array containing numbers whose cumulative product is desired. If arr is not an array, a conversion is attempted.*
- *axis : Axis along which the cumulative product is computed. The default is to compute the product of the flattened array.*
- *dtype : Type of the returned array, as well as of the accumulator in which the elements are multiplied. If dtype is not specified, it defaults to the dtype of arr, unless arr has an integer dtype with a precision less than that of the default platform integer. In that case, the default platform integer is used instead.*
- *out : [ndarray, optional] A location into which the result is stored.
  -> If provided, it must have a shape that the inputs broadcast to.
  -> If not provided or None, a freshly-allocated array is returned.*
  
*Return : A new array holding the result is returned unless out is specified, in which case it is returned.*


In [18]:
# Example 1 - working

Number = 10
  
print ("Input  number : ", Number)
    
Result = np.cumprod(Number) 
print ("cumulative product of input number : ", Result) 

Input  number :  10
cumulative product of input number :  [10]


In the above Example We have taken a number and assign that number into a variable, then we have computed the `np.cumprod` funtion on that Variable which give us the " Cumulative Product " of that number.

In [19]:
# Example 2 - working

Numbers = np.array([[2, 4, 6], [1, 3, 5]])
   
print ("Input array : ", Numbers) 
    
Result = np.cumprod(Numbers) 
print ("cumulative product of array elements: ", Result) 


Input array :  [[2 4 6]
 [1 3 5]]
cumulative product of array elements:  [  2   8  48  48 144 720]


Here we are going to compute the " Cumulative Product " on an NumPy array and store the Result in the "Result" Variable and Print that Result. but here we can see that the Result is Computed in the single list of array elements.

In [20]:
# Example 3 - Workking

Numbers = np.array([[2, 4, 6], [1, 3, 5]])
   
print ("Input array : ", Numbers) 
    
Result = np.cumprod(Numbers, axis = 1) 
print ("cumulative product of array elements taking axis 1: ", Result)

Input array :  [[2 4 6]
 [1 3 5]]
cumulative product of array elements taking axis 1:  [[ 2  8 48]
 [ 1  3 15]]


In the Example above we have computed the results of NumPy Array by `np.cumprod` fuction but here we have given the " axis = 1 " so the results is going to be computed Column Wise. and we can clearly see that.

In [21]:
# Example 4 - Working

Numbers = np.array([[1, 4, 6], [1, 3, 5]])
   
print ("Input array : ", Numbers) 
    
Result = np.cumprod(Numbers, axis = 0) 
print ("cumulative product of array elements taking axis 1: ", Result)

Input array :  [[1 4 6]
 [1 3 5]]
cumulative product of array elements taking axis 1:  [[ 1  4  6]
 [ 1 12 30]]


Examples 4 Shows the Computation of `np.cumprod` Function on an NumPy array by keeping the " axis = 0 " which will compute the Result Row Wise.

##### Example 5 - Breaking

In [22]:
Numbers = np.array([[4, 6], [1, 3, 5]])
   
print ("Input array : ", Numbers) 
    
Result = np.cumprod(Numbers) 
print ("cumulative product of array elements taking axis 1: ", Result)


Input array :  [list([4, 6]) list([1, 3, 5])]


/tmp/ipykernel_35/4123106660.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  Numbers = np.array([[4, 6], [1, 3, 5]])


TypeError: can't multiply sequence by non-int of type 'list'

##### How To Resolve it-

As we can see in the above example we have given the Array of different lengths so the function `np.cumprod` does not able to compute the Cumulative Product of the given array, So to perform this computation we need to take the Arrays of same length as we have taken in the above four Examples.


When we need to compute the " Cumulative Product " of any NumPy Array we can use `np.cumprod` function as it very useful function to compute the Cumulative Product.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "deepakkumawat2120/5-numpy-functions-you-might-not-know" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know


'https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know'

## Function 5 - numpy.matmul

#### numpy.matmul - It Gives the Matrix Product of Two Arrays.

![](https://help.scilab.org/docs/6.0.2/pt_BR/MATMUL.png)

***Parameters : x1, x2 :array_like***
- *Input arrays, scalars not allowed.*

- ___out___ : ***ndarray,optional***
> *A location into which the result is stored. If provided, it must have a shape that matches the signature (n,k),(k,m)->(n,m). If not provided or None, a freshly-allocated array is returned.*

***Returns : y : ndarray***
- *The matrix product of the inputs. This is a scalar only when both x1, x2 are 1-d vectors.*

***Raises : ValueError***
- *If the last dimension of x1 is not the same size as the second-to-last dimension of x2.*
- *If a scalar value is passed in.*




In [24]:
# Example 1 - working

Matrix_a = np.array([[1, 0],
                    [0, 1]])
Matrix_b = np.array([[4, 1],
                    [2, 2]])
print("Input Matrix:\n", Matrix_a,'\n',Matrix_b)
print('')

Results = np.matmul(Matrix_a, Matrix_b)

print('The Multiplication of the two Matrix is:\n', Results)

Input Matrix:
 [[1 0]
 [0 1]] 
 [[4 1]
 [2 2]]

The Multiplication of the two Matrix is:
 [[4 1]
 [2 2]]


In the above example we have taken  Two NumPy array and Assign Them into the Variable " Matrix_a and Matrix_b " and then we have computed the Matrix Multiplication using `np.matmul` funtion and store that into Results Variable and Print the values inside the Results.

In [25]:
# Example 2 - working

Matrix_a = np.array([[1, 0],
                    [0, 1]])
Matrix_b = np.array([1, 2])

print('Input Matrix:\n', Matrix_a,',',Matrix_b)
print('')

Result = np.matmul(Matrix_a, Matrix_b)

print('The Multiplicaton of the two Matrix is:\n', Result)

Input Matrix:
 [[1 0]
 [0 1]] , [1 2]

The Multiplicaton of the two Matrix is:
 [1 2]


Here we have Computed the Result of Multiplication of a 2-D and 1-D array and The result is as usual as we got in the Example 1 and we have print the result as seen above.

##### Example 3 - breaking

In [26]:
a = [1,2]
b = 3
np.matmul(a,b)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

##### How to Resolve it-
Here in the Above example we are not able to get the multiplication using `np.matmul` because we are not able to compute the Scalar Multiplication so it Raises an Error, and to make it work we need to add an element to it.

`np.matmul` is a very useful function to compute the matrix multiplication of an array.

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "deepakkumawat2120/5-numpy-functions-you-might-not-know" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know


'https://jovian.ai/deepakkumawat2120/5-numpy-functions-you-might-not-know'

## Conclusion

In this notebook we saw 5 of the most used functions in the popular library numpy . There are a lot more important functions like this in the numpy module. To know more about numpy check the numpy docs(link given below). This library is widely used in the field of Data Science along with other libraries like pandas, pytorch etc. This library is a lot faster than normal pyhon list objects therefore this can be used in programs and mathematical functions too, to speed up the process.



## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Geeks for Geeks Website : https://www.geeksforgeeks.org/python-numpy/
* Jovian :  https://jovian.ai/learn/zero-to-data-analyst-bootcamp/lesson/numerical-computing-with-numpy

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>